[2024-09-01T10:45:12.936+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T10:45:13.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.branch_task manual__2024-09-01T10:45:05.574626+00:00 [queued]>
[2024-09-01T10:45:13.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.branch_task manual__2024-09-01T10:45:05.574626+00:00 [queued]>
[2024-09-01T10:45:13.233+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-01T10:45:13.259+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-09-01 10:45:05.574626+00:00
[2024-09-01T10:45:13.269+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6314) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T10:45:13.272+0000] {standard_task_runner.py:64} INFO - Started process 6316 to run task
[2024-09-01T10:45:13.272+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'branch_task', 'manual__2024-09-01T10:45:05.574626+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp6q7908do']
[2024-09-01T10:45:13.276+0000] {standard_task_runner.py:91} INFO - Job 378: Subtask branch_task
[2024-09-01T10:45:13.349+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_dag.branch_task manual__2024-09-01T10:45:05.574626+00:00 [running]> on host 19bb8daff211
[2024-09-01T10:45:13.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T10:45:05.574626+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T10:45:05.574626+00:00'
[2024-09-01T10:45:13.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T10:45:13.533+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-01T10:45:13.551+0000] {python.py:237} INFO - Done. Returned value was: send_email
[2024-09-01T10:45:13.552+0000] {branch.py:36} INFO - Branch into send_email
[2024-09-01T10:45:13.553+0000] {skipmixin.py:178} INFO - Following branch send_email
[2024-09-01T10:45:13.580+0000] {skipmixin.py:246} INFO - Skipping tasks [('processing_data', -1)]
[2024-09-01T10:45:13.617+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T10:45:13.648+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=branch_task, run_id=manual__2024-09-01T10:45:05.574626+00:00, execution_date=20240901T104505, start_date=20240901T104513, end_date=20240901T104513
[2024-09-01T10:45:13.690+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T10:45:13.737+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T10:45:13.744+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
