[2024-09-01T14:20:34.948+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T14:20:35.959+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Apriori_project.send_failure_email scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-01T14:20:36.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Apriori_project.send_failure_email scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-01T14:20:36.018+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-01T14:20:36.091+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_failure_email> on 2024-08-31 00:00:00+00:00
[2024-09-01T14:20:36.116+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=7873) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T14:20:36.124+0000] {standard_task_runner.py:64} INFO - Started process 7875 to run task
[2024-09-01T14:20:36.119+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Apriori_project', 'send_failure_email', 'scheduled__2024-08-31T00:00:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmplyr3_6z_']
[2024-09-01T14:20:36.128+0000] {standard_task_runner.py:91} INFO - Job 409: Subtask send_failure_email
[2024-09-01T14:20:36.397+0000] {task_command.py:426} INFO - Running <TaskInstance: Apriori_project.send_failure_email scheduled__2024-08-31T00:00:00+00:00 [running]> on host 19bb8daff211
[2024-09-01T14:20:36.913+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='jorgepons90@gmail.com' AIRFLOW_CTX_DAG_OWNER='Jorge Pons' AIRFLOW_CTX_DAG_ID='Apriori_project' AIRFLOW_CTX_TASK_ID='send_failure_email' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-31T00:00:00+00:00'
[2024-09-01T14:20:36.917+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T14:20:37.113+0000] {base.py:84} INFO - Using connection ID 'smtp_default' for task execution.
[2024-09-01T14:20:37.116+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-09-01T14:20:37.989+0000] {email.py:282} INFO - Sent an alert email to ['algenet4.jpons@gmail.com']
[2024-09-01T14:20:39.004+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T14:20:39.048+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Apriori_project, task_id=send_failure_email, run_id=scheduled__2024-08-31T00:00:00+00:00, execution_date=20240831T000000, start_date=20240901T142035, end_date=20240901T142039
[2024-09-01T14:20:39.173+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-01T14:20:39.263+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T14:20:39.275+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
